/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FestivalsRouteImport } from './routes/festivals'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as SearchRouteImport } from './routes/search'
import { Route as YearsRouteImport } from './routes/years'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityLogsRouteImport } from './routes/admin/activity-logs'
import { Route as AdminAlbumsRouteImport } from './routes/admin/albums'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminEditorsRouteImport } from './routes/admin/editors'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminFestivalsRouteImport } from './routes/admin/festivals'
import { Route as AdminImageGalleryRouteImport } from './routes/admin/image-gallery'
import { Route as AdminImagesRouteImport } from './routes/admin/images'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPrivateArchiveRouteImport } from './routes/admin/private-archive'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTrashRouteImport } from './routes/admin/trash'
import { Route as AdminVideosRouteImport } from './routes/admin/videos'
import { Route as AdminYearsRouteImport } from './routes/admin/years'
import { Route as AlbumAlbumIdRouteImport } from './routes/album.$albumId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsRoute = FestivalsRouteImport.update({
  id: '/festivals',
  path: '/festivals',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const YearsRoute = YearsRouteImport.update({
  id: '/years',
  path: '/years',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/admin/activity-logs',
  path: '/admin/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlbumsRoute = AdminAlbumsRouteImport.update({
  id: '/admin/albums',
  path: '/admin/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorsRoute = AdminEditorsRouteImport.update({
  id: '/admin/editors',
  path: '/admin/editors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFestivalsRoute = AdminFestivalsRouteImport.update({
  id: '/admin/festivals',
  path: '/admin/festivals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImageGalleryRoute = AdminImageGalleryRouteImport.update({
  id: '/admin/image-gallery',
  path: '/admin/image-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImagesRoute = AdminImagesRouteImport.update({
  id: '/admin/images',
  path: '/admin/images',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrivateArchiveRoute = AdminPrivateArchiveRouteImport.update({
  id: '/admin/private-archive',
  path: '/admin/private-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrashRoute = AdminTrashRouteImport.update({
  id: '/admin/trash',
  path: '/admin/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/admin/videos',
  path: '/admin/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminYearsRoute = AdminYearsRouteImport.update({
  id: '/admin/years',
  path: '/admin/years',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumIdRoute = AlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/developer': typeof DeveloperRoute
  '/favorites': typeof FavoritesRoute
  '/festivals': typeof FestivalsRoute
  '/images': typeof ImagesRoute
  '/search': typeof SearchRoute
  '/years': typeof YearsRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/albums': typeof AdminAlbumsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/editors': typeof AdminEditorsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/festivals': typeof AdminFestivalsRoute
  '/admin/image-gallery': typeof AdminImageGalleryRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/private-archive': typeof AdminPrivateArchiveRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/years': typeof AdminYearsRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/developer': typeof DeveloperRoute
  '/favorites': typeof FavoritesRoute
  '/festivals': typeof FestivalsRoute
  '/images': typeof ImagesRoute
  '/search': typeof SearchRoute
  '/years': typeof YearsRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/albums': typeof AdminAlbumsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/editors': typeof AdminEditorsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/festivals': typeof AdminFestivalsRoute
  '/admin/image-gallery': typeof AdminImageGalleryRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/private-archive': typeof AdminPrivateArchiveRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/years': typeof AdminYearsRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/developer': typeof DeveloperRoute
  '/favorites': typeof FavoritesRoute
  '/festivals': typeof FestivalsRoute
  '/images': typeof ImagesRoute
  '/search': typeof SearchRoute
  '/years': typeof YearsRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/albums': typeof AdminAlbumsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/editors': typeof AdminEditorsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/festivals': typeof AdminFestivalsRoute
  '/admin/image-gallery': typeof AdminImageGalleryRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/private-archive': typeof AdminPrivateArchiveRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trash': typeof AdminTrashRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/years': typeof AdminYearsRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums'
    | '/developer'
    | '/favorites'
    | '/festivals'
    | '/images'
    | '/search'
    | '/years'
    | '/admin/activity-logs'
    | '/admin/albums'
    | '/admin/analytics'
    | '/admin/editors'
    | '/admin/events'
    | '/admin/festivals'
    | '/admin/image-gallery'
    | '/admin/images'
    | '/admin/login'
    | '/admin/private-archive'
    | '/admin/settings'
    | '/admin/trash'
    | '/admin/videos'
    | '/admin/years'
    | '/album/$albumId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums'
    | '/developer'
    | '/favorites'
    | '/festivals'
    | '/images'
    | '/search'
    | '/years'
    | '/admin/activity-logs'
    | '/admin/albums'
    | '/admin/analytics'
    | '/admin/editors'
    | '/admin/events'
    | '/admin/festivals'
    | '/admin/image-gallery'
    | '/admin/images'
    | '/admin/login'
    | '/admin/private-archive'
    | '/admin/settings'
    | '/admin/trash'
    | '/admin/videos'
    | '/admin/years'
    | '/album/$albumId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/developer'
    | '/favorites'
    | '/festivals'
    | '/images'
    | '/search'
    | '/years'
    | '/admin/activity-logs'
    | '/admin/albums'
    | '/admin/analytics'
    | '/admin/editors'
    | '/admin/events'
    | '/admin/festivals'
    | '/admin/image-gallery'
    | '/admin/images'
    | '/admin/login'
    | '/admin/private-archive'
    | '/admin/settings'
    | '/admin/trash'
    | '/admin/videos'
    | '/admin/years'
    | '/album/$albumId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRoute: typeof AlbumsRoute
  DeveloperRoute: typeof DeveloperRoute
  FavoritesRoute: typeof FavoritesRoute
  FestivalsRoute: typeof FestivalsRoute
  ImagesRoute: typeof ImagesRoute
  SearchRoute: typeof SearchRoute
  YearsRoute: typeof YearsRoute
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminAlbumsRoute: typeof AdminAlbumsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminEditorsRoute: typeof AdminEditorsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFestivalsRoute: typeof AdminFestivalsRoute
  AdminImageGalleryRoute: typeof AdminImageGalleryRoute
  AdminImagesRoute: typeof AdminImagesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPrivateArchiveRoute: typeof AdminPrivateArchiveRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrashRoute: typeof AdminTrashRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminYearsRoute: typeof AdminYearsRoute
  AlbumAlbumIdRoute: typeof AlbumAlbumIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals': {
      id: '/festivals'
      path: '/festivals'
      fullPath: '/festivals'
      preLoaderRoute: typeof FestivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/years': {
      id: '/years'
      path: '/years'
      fullPath: '/years'
      preLoaderRoute: typeof YearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/admin/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/albums': {
      id: '/admin/albums'
      path: '/admin/albums'
      fullPath: '/admin/albums'
      preLoaderRoute: typeof AdminAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editors': {
      id: '/admin/editors'
      path: '/admin/editors'
      fullPath: '/admin/editors'
      preLoaderRoute: typeof AdminEditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/festivals': {
      id: '/admin/festivals'
      path: '/admin/festivals'
      fullPath: '/admin/festivals'
      preLoaderRoute: typeof AdminFestivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/image-gallery': {
      id: '/admin/image-gallery'
      path: '/admin/image-gallery'
      fullPath: '/admin/image-gallery'
      preLoaderRoute: typeof AdminImageGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/images': {
      id: '/admin/images'
      path: '/admin/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AdminImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/private-archive': {
      id: '/admin/private-archive'
      path: '/admin/private-archive'
      fullPath: '/admin/private-archive'
      preLoaderRoute: typeof AdminPrivateArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trash': {
      id: '/admin/trash'
      path: '/admin/trash'
      fullPath: '/admin/trash'
      preLoaderRoute: typeof AdminTrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/admin/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/years': {
      id: '/admin/years'
      path: '/admin/years'
      fullPath: '/admin/years'
      preLoaderRoute: typeof AdminYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId': {
      id: '/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRoute,
  DeveloperRoute: DeveloperRoute,
  FavoritesRoute: FavoritesRoute,
  FestivalsRoute: FestivalsRoute,
  ImagesRoute: ImagesRoute,
  SearchRoute: SearchRoute,
  YearsRoute: YearsRoute,
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminAlbumsRoute: AdminAlbumsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminEditorsRoute: AdminEditorsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFestivalsRoute: AdminFestivalsRoute,
  AdminImageGalleryRoute: AdminImageGalleryRoute,
  AdminImagesRoute: AdminImagesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPrivateArchiveRoute: AdminPrivateArchiveRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrashRoute: AdminTrashRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminYearsRoute: AdminYearsRoute,
  AlbumAlbumIdRoute: AlbumAlbumIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
